version: "3"
services:
 
  web:
   build: ./myapp
   ports:
      - "8080:80"
   volumes:
      - '.:/app'
   environment:
      - SYMFONY_PROJECT_NAME=myapp
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase

  postgres:
    build: ./postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./postgres/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - 5432:5432

  adminer:
    build: ./adminer
    ports:
      - 8081:8080

volumes:
  pgdata:
    