version: "3"
services:
  
  adminer:
    build: ./adminer
    ports:
      - 8081:8080
  
  web:
   build: ./symfony
   ports:
      - "8080:9000"
   volumes:
      - ./symfony:/var/www/html
    

  
 

