version: "3"
services:
  adminer:
    build: ./adminer
    ports:
      - 8081:8080
  
  web:
   build: ./symfony
   ports:
      - "8080:9000"
   volumes:
      - '.:/app'
   environment:
      - SYMFONY_PROJECT_NAME=myapp

  postgres:
    build: ./postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  
 

