version: "3"
services:
 
  web:
   build: ./myapp
   ports:
      - "8080:80"
   volumes:
      - '.:/app'
   environment:
      - SYMFONY_PROJECT_NAME=myapp
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase

  db:
    build: ./postgres
    container_name: container_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    user: postgres
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - 5432:5432

  adminer:
    image: taslima13/docker-project_adminer:latest
    ports:
      - 8081:8080

volumes:
  pgdata:
    

  
 

